Ds 2667
Displayr/flipAnalysisOfVariance pull request #2
Opened 2019-11-14 03:37 UTC by chschan

2019-11-18 01:30 UTC, jrwishart commented on R/segmentcomparisontable.R
> +        rownames(pvals) <- row.labels
Code fails here due to a dimension mismatch when PickOneMulti input is used. See Routput throwing error in https://app.displayr.com/Dashboard?project_id=-705348#page=5a67bf81-8b62-4800-8cd1-64675dfba945

2019-11-18 01:44 UTC, jrwishart commented on R/segmentcomparisontable.R
> +        tmp.numeric <- isTRUE(attr(x[[vvi]], "questiontype") %in% c("NumberMulti", "Number"))
This might need "NumberGrid" as well?

2019-11-18 01:47 UTC, jrwishart requested changes
Currently errors with some input variable types and numeric data isn't displaying as numeric (displaying as percentage). More information and reproducible examples in the comments.

2019-11-18 05:47 UTC, jrwishart commented
Changes have fixed the `PickOneMulti` and `NumberGrid` input type errors. However, the data reduction is still visible when the user toggles `Show NET or SUM`
![image](https://user-images.githubusercontent.com/4605715/69027451-11622800-0a23-11ea-8edc-4042fee7d8ae.png)

2019-11-19 00:20 UTC, chschan commented
Fixed now. I have replaced the `Show NET or SUM` checkbox with a textbox `Rows to hide`, for consistency with the other Visualization/Table Standard R pages. The new form is on the page titled "Version 3": https://app.displayr.com/Dashboard?project_id=-705348#page=04606268-e538-422f-9e93-4d6ce626aca2

2019-11-19 02:24 UTC, merged